package com.innova.facturas.facturasinnovaservices.mapper;

import com.innova.facturas.facturasinnovaservices.model.dto.FacturaDto;
import com.innova.facturas.facturasinnovaservices.model.entity.Factura;

public class FacturaMapper {

    public static FacturaDto mapToFacturaDto(Factura factura) {
        return new FacturaDto(
                factura.getIdFactura(),
                factura.getEmpresa(),
                factura.getTipoFactura(),
                factura.getTimbradoFactura(),
                factura.getCdcFactura(),
                factura.getCodigoControlFactura(),
                factura.getNumeroFactura(),
                factura.getRucEmisorFactura(),
                factura.getRazonSocialEmisorFactura(),
                factura.getRucReceptorFactura(),
                factura.getRazonSocialReceptorFactura(),
                factura.getCondicionVentaFactura(),
                factura.getFechaInicioVigenciaFactura(),
                factura.getFechaFinVigenciaFactura(),
                factura.getFechaEmisionFactura(),
                factura.getMontoTotalFacturaGs(),
                factura.getMontoTotalIvaFacturaGs(),
                factura.getMontoCincoFacturaGs(),
                factura.getMontoDiezFacturaGs(),
                factura.getExentaFacturaGs(),
                factura.getGravadaCincoGs(),
                factura.getGravadaDiezGs(),
                factura.getGravadaExentaGs(),
                factura.getStatusFactura(),
                factura.getMonedaExtranjera(),
                factura.getTipoRegistro(),
                factura.getTipoComprobante(),
                factura.getDetalleComprobante(),
                factura.getTipoDocumento(),
                factura.getImputaIva(),
                factura.getImputaIre(),
                factura.getImputaIrpRsp(),
                factura.getComprobanteAsociado(),
                factura.getTimbradoComprobanteAsociado(),
                factura.getStatusSet(),
                factura.getRg90Generado(),
                factura.getContadorRg90(),
                factura.getCliente(),
                factura.getTipoMoneda(),
                factura.getCotizacionCompra(),
                factura.getCotizacionVenta(),
                factura.getGravadaExentaMoneda(),
                factura.getGravadaCincoMoneda(),
                factura.getGravadaDiezMoneda(),
                factura.getTotalGravadaMoneda(),
                factura.getExentaMoneda(),
                factura.getIvaCincoMoneda(),
                factura.getIvaDiezMoneda(),
                factura.getTotalIvaMoneda(),
                factura.getCreatedAt(),
                factura.getCreatedBy(),
                factura.getUpdatedAt(),
                factura.getUpdatedBy());
    }

    public static Factura mapToFactura(FacturaDto facturaDto) {
        return new Factura(
                facturaDto.getIdFactura(),
                facturaDto.getEmpresa(),
                facturaDto.getTipoFactura(),
                facturaDto.getTimbradoFactura(),
                facturaDto.getCdcFactura(),
                facturaDto.getCodigoControlFactura(),
                facturaDto.getNumeroFactura(),
                facturaDto.getRucEmisorFactura(),
                facturaDto.getRazonSocialEmisorFactura(),
                facturaDto.getRucReceptorFactura(),
                facturaDto.getRazonSocialReceptorFactura(),
                facturaDto.getCondicionVentaFactura(),
                facturaDto.getFechaInicioVigenciaFactura(),
                facturaDto.getFechaFinVigenciaFactura(),
                facturaDto.getFechaEmisionFactura(),
                facturaDto.getMontoTotalFacturaGs(),
                facturaDto.getMontoTotalIvaFacturaGs(),
                facturaDto.getMontoCincoFacturaGs(),
                facturaDto.getMontoDiezFacturaGs(),
                facturaDto.getExentaFacturaGs(),
                facturaDto.getGravadaCincoGs(),
                facturaDto.getGravadaDiezGs(),
                facturaDto.getGravadaExentaGs(),
                facturaDto.getStatusFactura(),
                facturaDto.getMonedaExtranjera(),
                facturaDto.getTipoRegistro(),
                facturaDto.getTipoComprobante(),
                facturaDto.getDetalleComprobante(),
                facturaDto.getTipoDocumento(),
                facturaDto.getImputaIva(),
                facturaDto.getImputaIre(),
                facturaDto.getImputaIrpRsp(),
                facturaDto.getComprobanteAsociado(),
                facturaDto.getTimbradoComprobanteAsociado(),
                facturaDto.getStatusSet(),
                facturaDto.getRg90Generado(),
                facturaDto.getContadorRg90(),
                facturaDto.getCliente(),
                facturaDto.getTipoMoneda(),
                facturaDto.getCotizacionCompra(),
                facturaDto.getCotizacionVenta(),
                facturaDto.getGravadaExentaMoneda(),
                facturaDto.getGravadaCincoMoneda(),
                facturaDto.getGravadaDiezMoneda(),
                facturaDto.getTotalGravadaMoneda(),
                facturaDto.getExentaMoneda(),
                facturaDto.getIvaCincoMoneda(),
                facturaDto.getIvaDiezMoneda(),
                facturaDto.getTotalIvaMoneda(),
                facturaDto.getCreatedAt(),
                facturaDto.getCreatedBy(),
                facturaDto.getUpdatedAt(),
                facturaDto.getUpdatedBy());
    }

}
